#!/usr/bin/env bash

def configure_nginx_custom_header():
    # Add custom header to Nginx configuration
    custom_header = "add_header X-Served-By $hostname;"
    nginx_conf_path = "/etc/nginx/nginx.conf"
    
    with open(nginx_conf_path, 'a') as nginx_conf:
        nginx_conf.write(custom_header)

configure_nginx_custom_header()
