#!/usr/bin/env bash
# Bash script to configure HAProxy on a new Ubuntu machine


# Install HAProxy
sudo apt update
sudo apt install haproxy -y

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo cat <<EOT >> /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend load_balancer
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    server web-01 {STUDENT_ID}-web-01:80 check
    server web-02 {STUDENT_ID}-web-02:80 check
EOT

# Restart HAProxy
sudo systemctl restart haproxy
